### ISSUE TITLE
From: name and email

### ISSUE THREAD

**Issue by kirkroberts** [xodigital/Formerly#10]
Is it possible to include a name in the from field of submission emails?
I tried `{name}<{email}>` and `{name} <{email}>` (with and without a space before the gt) with no success. Of course I have a name field in the form.

p.s. – thank you for making this and offering it to others.

**Comment by MartyWallace** [comment]
Hi @kirkroberts; you're now able to optionally use the format `Name <email>` in the from column :-)

**Comment by kirkroberts** [comment]
That's great, thanks! I'll give it a spin soon.
