### ISSUE TITLE
Selected attribute of the option element for the Formerly form select element is not set when an entry is loaded

### ISSUE THREAD

**Issue by kperusko** [xodigital/Formerly#17]
Steps to reproduce:
1. Create a new field of type Formerly form.
2. Associate the field with one entry (e.g. News entry). 
3. Create two different forms in Formerly - "Form A", "Form B".
4. Add new entry of type News and select a second value from the select element.
5. Save and reload entry.

The reloaded entry will have wrong item option selected (the first option is displayed as "selected" instead of the second option that we selected).

**Comment by portnull** [comment]
I have the exact same problem.

**Comment by wiso1234** [comment]
fixed in 1.3.1 15253789a318c2c1d9e0697d5f90213c0ca9beea
