### ISSUE TITLE
Submission problem

### ISSUE THREAD

**Issue by spotd** [xodigital/Formerly#22]
Just installed on - Craft Pro 2.3.2643

Captures submissions and works great in admin, but the template throws the below error on submission

Craft\Formerly_SubmissionModel and its behaviours do not have a method or closure named "contactForm_name".

Anything i can do? Be good to stick with this plugin as it has the neatest design

**Comment by spotd** [comment]
I have fixed this issue. Its not documented, but realised you need to match the email vars, in my case {name} had to become {firstName}. All working great.

**Comment by wiso1234** [comment]
1.3.2 handles this much nicer, it just leaves the tag unreplaced if it doesn't match
