### ISSUE TITLE
Export - Limited to 100 entries

### ISSUE THREAD

**Issue by nevsie** [xodigital/Formerly#24]
I undersatnd this has probably be done for effiency - but useless when i have 900+ to export and no way to modify Formerly to handle it!

**Comment by nevsie** [comment]
To answer what i have done "for now". in file:
formerly/controllers/Formerly_ExportController.php

At around line 19/20 i changed:

		$criteria = craft()->elements->getCriteria('Formerly_Submission');
		$criteria->formId = $formId;

to:

		$criteria = craft()->elements->getCriteria('Formerly_Submission');
		$criteria->limit = -1;
		$criteria->formId = $formId;

i.e. simply set a negative number for the limit to mean all values.

**Comment by wiso1234** [comment]
fixed in 1.3.1 15253789a318c2c1d9e0697d5f90213c0ca9beea
