### ISSUE TITLE
Feature Request - General Text Field

### ISSUE THREAD

**Issue by nevsie** [xodigital/Formerly#26]
It would be great if there was a general text / HTML field option for the form builder part. 

For example in my current simple form i just needed to add a title to a section of the form. A simple general text field would do this nicely.

But i think this plugin is out of dev / or maybe even dead now, so not sure this is somehting that needs to be forked and continued elsewhere?

**Comment by wiso1234** [comment]
done in 1.3.2 (RawHTML question type)
