### ISSUE TITLE
enableCsrfProtection

### ISSUE THREAD

**Issue by spotd** [xodigital/Formerly#30]
Is shaping up to be the neatest forms solution in my view ( I have tried a few). Only snag i found is if you have enableCsrfProtection in the config you cant edit forms in admin. Should be an easy fix.
Cheers for adding honeypot.

**Comment by wiso1234** [comment]
oh yes thanks for that, I'll push the fix in the next release.

For now it's a simple fix 

add 	{{ getCsrfInput() }} to the top of templates/forms/_edit.html

**Comment by wiso1234** [comment]
or if you are not up to messing with the plugin code, turn off csrf while editing the form :P

**Comment by spotd** [comment]
Thanks... Thats what i had done. Nice plugin
