### ISSUE TITLE
Spam prevention?

### ISSUE THREAD

**Issue by mccombs** [xodigital/Formerly#31]
Is there any easy way to prevent spam with Formerly?

**Comment by wiso1234** [comment]
Yes you can,

you add this to the craft general.php

'formerly' => array(
			'honeyPotName' => 'pants', //id of input honeypot, don't call it something obvious like honeypot
	);

and this to your form template

	{% if craft.config.formerly is defined and craft.config.formerly.honeyPotName is defined %}
				<input type="text" id="formerly-hp-sec" name="{{ craft.config.formerly.honeyPotName }}" />
			{% endif %}

if input is entered into that textbox, formerly will return without error but not posting the data

**Comment by mccombs** [comment]
Thanks I posted this before realizing the plugin was updated!
