### ISSUE TITLE
Pretty emails

### ISSUE THREAD

**Issue by mccombs** [xodigital/Formerly#34]
While not critical it would be great to see email notifications be sent out in a "pretty" format. Wufoo for example has really pretty HTML. 

I was going to make the edit myself but it looks like I can't because of how the submission information is being complied before it's sent. It looks as if the formatting happens before the body is even called

Would it be possible to add something like this in?

**Comment by thisisjamessmith** [comment]
You can hack around this by putting a twig include into the body field and then passing the submission id through to a template. However, you need to replace curly braces with 3 angled brackets like this so it gets parsed successfully:

`<<<% include '_emails/your-pretty-email-template' with <<<'id':{id}>>> %>>>`

Then your template would be along these lines:


```
{% set submission = craft.formerly.submissions.id(id).first %}
<html>
	<body>
		<ul>
			<li>First name: {{ submission.formHandle_firstName }}</li>
		</ul>
	</body>
</html>
```
