### ISSUE TITLE
HoneyPot does not appear to be working

### ISSUE THREAD

**Issue by nevsie** [xodigital/Formerly#41]
1.3.3
I have created a simple form. Added the config for honeypot, the field is displaying on front end in form (as expected till i hide it).
I submitted twice, once with it empty, once with content in the honey pot field.

Both went into DB and both arrived as emails?

I'll dig into it - but letting you know at this point. N

**Comment by nevsie** [comment]
Okay, i believe the issue is the same as we have come across before for different PHP versions.

File: Formerly_SubmissionService.php

Line 69 was:
$honeyPotName =  craft()->config->get(Formerly_ConfigSettings::SettingsGroupName, Formerly_ConfigSettings::HoneyPotName);

Changed to:
$honeyPotName = craft()->config->get(Formerly_ConfigSettings::SettingsGroupName)[Formerly_ConfigSettings::HoneyPotName];

Honeypot now works for me...

**Comment by wiso1234** [comment]
I am confused, I thought we changed it to that because people were reporting the other way wasn't working in older versions of php. If someone can advise me on what code will work across all versions of php I'll push a fix up

**Comment by wiso1234** [comment]
I just had the same issue testing the new sendEmails and writeEmailBodyToFilePath settings. I've changed all settings code to use the format you specify

**Comment by nevsie** [comment]
Yup, Sorry i know! Just throwing things up as i come across them on various different sites! It is a PHP version thing - solution, dunno tedious!
http://craftcms.stackexchange.com/questions/10213/getting-environmental-variable-via-plugin
