### ISSUE TITLE
Line breaks on e-mails not showing up?

### ISSUE THREAD

**Issue by RitterKnightCreative** [xodigital/Formerly#43]
Appears line breaks are not being output on the e-mails. It's all running together on one line.
![screen shot 2015-09-18 at 4 45 32 pm](https://cloud.githubusercontent.com/assets/3707869/9971851/b8c3c6f8-5e24-11e5-9b63-130a526ead1b.png)
![screen shot 2015-09-18 at 4 46 32 pm](https://cloud.githubusercontent.com/assets/3707869/9971872/e35f6066-5e24-11e5-92c6-fed72fead3c3.png)

**Comment by wiso1234** [comment]
It sends html emails, so add some markup, add <br /> or wrap it in p tags. I can see why you are confused, the default email doesn't have this markup.

We'll update the default email it creates to have html.

**Comment by wiso1234** [comment]
done in latest release
