### ISSUE TITLE
Problem saving form

### ISSUE THREAD

**Issue by cole007** [xodigital/Formerly#59]
We've got a large custom form which has problems saving forms with more than eleven fields.
Any idea why this might be a problem?

**Comment by wiso1234** [comment]
We've done one recently with 30+ fields. Can you give some more details on what the problems are

**Comment by cole007** [comment]
The form is not in itself particularly large but it does have a lot of dropdown fields in.
See attached. Many thanks

![download](https://cloud.githubusercontent.com/assets/855195/11586002/f13664b2-9a67-11e5-8a67-565f7fe34540.png)

**Comment by wiso1234** [comment]
There is a php limit on the number inputs on the page. You may have reached  that.  You can increase it in php.ini

<div>-------- Original message --------</div><div>From: Cole Henley <notifications@github.com> </div><div>Date:04/12/2015  8:18 PM  (GMT+10:30) </div><div>To: xodigital/Formerly <Formerly@noreply.github.com> </div><div>Cc: Andrew Wisener <wisenerandrew@gmail.com> </div><div>Subject: Re: [Formerly] Problem saving form (#59) </div><div>
</div>The form is not in itself particularly large but it does have a lot of dropdown fields in.
See attached. Many thanks

**Comment by cole007** [comment]
Thanks - looked into this. Currently set to 1000 which is nowhere near the number we are trying to save.

**Comment by cole007** [comment]
We've got to the bottom of this. There were duplicate Field names in the form. 

Ideally it would be good to be able to split out the field name and field label and specify each of these separately.
