### ISSUE TITLE
Feature request: ability to remove submissions from admin

### ISSUE THREAD

**Issue by johanandre** [xodigital/Formerly#7]

**Comment by MartyWallace** [comment]
@johanandre Would the data be deleted entirely or would you say some kind of 'archive' would make more sense? I assume if the latter that the archive would only be accessible on an admin account, not a client account.

**Comment by johanandre** [comment]
@MartyWallace That sounds terrific!

**Comment by noisysocks** [comment]
Hi @johanandre, I've added the ability to delete form submissions in 1.2.0.
