### ISSUE TITLE
Date formatting notifications

### ISSUE THREAD

**Issue by cole007** [xodigital/Formerly#71]
Is there any way to control the formatting of dates sent by email?
Defaulting to YYYY-MM-DD in notifications despite the formatting set for the locale.

**Comment by wiso1234** [comment]
Hi Cole,

The email template is essentially a twig template and we use the craft
rendering engine to produce the email body.

See line 253 of
https://github.com/xodigital/Formerly/blob/master/services/Formerly_SubmissionsService.php

So I think this means you can add twig filters to your email copy so
something like { myDate|date('jS F Y') }.

Give it a go and let us know if it works

regards

Andrew

**Comment by wiso1234** [comment]
oh actually no that won't work :(

We go through every tag on the mail template and confirm the tagname is
valid. This was to ensure that we didn't get runtime errors on the site
when trying to send the email (craft would throw a really obscure error
that was confusing everyone).

So it matches the text between the braces to confirm that is a valid tagname

preg_match_all('/{([^}]*)}/', $template, $matches);

We should enhance that to allow for filters in tag,

**Comment by wiso1234** [comment]
I've fixed the template filtering code to allow twig filters to be used. So now you can add twig filters to format dates
