### ISSUE TITLE
HTML5 required attribute makes Chrome display a tooltip that collide with our validators

### ISSUE THREAD

**Issue by migswd** [xodigital/Formerly#75]
Big problem here with Chrome and Required HTML5 attribute.
Formerly add the HTML5 required attribute on mandatory fields which makes Chrome display a tooltip with a message "Please Fill out This Field".
So first it is not translatable and is confusing with our own validators.
See here
http://stackoverflow.com/questions/5392882/chrome-popup-please-fill-out-this-field/5393041#5393041

This attribute should not be added. Or have an option to disable it.

**Comment by wiso1234** [comment]
Hi Miguel,

The code to generate a form in formerly is really only meant as a guide for
developers to base their implementation on.

If you have an improvement please submit it and we'll happily add it to the
template.

The code you are referring to is easy to change, look for

{% if question.required %}
required
aria-required="true"
data-val-required="'{{ question.name }}' is required"
data-val="true"
{% endif %}

in the template and change as needed

regards

Andrew

**Comment by migswd** [comment]
Sorry but I do not really understand what to do.

Do you mean I just remove required condition in the input text template ?
But in that case my modification will be lost when I update your plugin no ?





Miguel

**Comment by wiso1234** [comment]
Hi Miguel,

Take a copy of the template and reference that so it won't get overwritten
by updates, then update the template as needed. The basic structure won't
change any time soon.

regards

Andrew
