### ISSUE TITLE
From name

### ISSUE THREAD

**Issue by iDzine** [xodigital/Formerly#79]
Maybe I'm missing something, but at the moment if a form is filled in, there's a mail being sent to the person who's filled in the form and to my client to notify him that there's a new form filled in.

The mail that my client is receiving states the name from within the Craft default FromName. This is confusing as he's receiving lot's of mails and he only sees his own company name (FromName) as Sender.

If he replies to the mail, then the mail si being answered to the customers email address, so this is fine, but I want to provide the visitors name as the Fromname to mails my client is receiving.

Searched through the formerly_submissionscontroller.php file and fiddled a bit with it, but can't get it to work... =(

So if any input for this, please do!

**Comment by georgeevans1995** [comment]
Hey iDzine, I had a similar issue and found this worked to fix the issue. Go to edit the form fields and in the emails section where you define who the emails get sent to add something like this:

`{firstName} {lastName}<{email}>`

using whatever field handles you want to use.

**Comment by iDzine** [comment]
Thought so that it was something silly I've been missing.
Thx @georgeevans1995 added the {name} field in front of the <{email}> and now it shows the senders name instead of the default site name.
Problem solved!!! :)
