### ISSUE TITLE
Error Error: Craft\Formerly_SubmissionModel and its behaviors do not have a method...

### ISSUE THREAD

**Issue by jeremyoniel** [xodigital/Formerly#8]
I recently installed the Formerly form plugin. The form works great and submissions are being stored in Craft. Unfortunately, when users hit submit I get this error:

Internal Server Error Craft\Formerly_SubmissionModel and its behaviors do not have a method or closure named "test_email".

Has anyone seen this issue? The "test" is my handle for the form. The documentation on the plugin is fairly limited, so I'm having trouble tracking down the issue. Any help would be greatly appreciated.

Jeremy

**Comment by noisysocks** [comment]
Hi Jeremy – do you think you could create a gist containing a dump of your `craft_formerly_questions` table so that I can investigate?

**Comment by lokeshreddy135** [comment]
I'm also having same error. It shows Craft\Formerly_SubmissionModel and its behaviors do not have a method or closure named  "hadle_email". I'm using my xampp for local testing and my e-mail environment is not setup properly. You think it's bcz of this or something else?

**Comment by dylantuohy** [comment]
Hi folks. Same error here. Has anyone found a solution?

**Comment by wiso1234** [comment]
Could this be the same as issue #22, fields in the emails need to be exactly the same as the fields in the form

**Comment by wiso1234** [comment]
sorted in 1.3.2 (doesn't crash if field names don't match)
