### ISSUE TITLE
Checkboxs are broken in current version (1.2)

### ISSUE THREAD

**Issue by mccombs** [xodigital/Formerly#9]
This was just a simple Yes/no checkbox. No label and the checkbox are spit out in groups of two.

Screenshot below

![screen shot 2015-01-27 at 2 31 55 pm](https://cloud.githubusercontent.com/assets/454117/5943381/0ca76caa-a6e4-11e4-9af7-d859e83096d5.png)

**Comment by alexbrindalsl** [comment]
I addressed this in https://github.com/xodigital/Formerly/pull/11 - so you can see the fixes there :)

**Comment by wiso1234** [comment]
sample fixed in 1.3.1 15253789a318c2c1d9e0697d5f90213c0ca9beea
